### ISSUE TITLE
NaNs in the ReRAM with conventional sequential

### ISSUE THREAD

**Issue by pavelgolikov** [neurosim/DNN_NeuroSim_V1.4#11]
Good day,

I am experimenting with Neurosim. I am running into a bit of an issue:

I am trying to evaluate the ReRAM in conventional sequential settings. I am using a single linear layer of size 1024. I am attaching the file with my parameter setting changes (the rest are the same as the ones in this repo):

![image](https://github.com/neurosim/DNN_NeuroSim_V1.4/assets/40681739/771b07f8-b1a2-48ef-8968-420cc2678626)

I have also modified the input vector to have only 1's in the ProcessingUnit.cpp as follows:

![image](https://github.com/neurosim/DNN_NeuroSim_V1.4/assets/40681739/cbe6a9e9-81f5-434f-af3a-b561dd406ce2)

When I run these settings, I get NaN's and Infs for some metrics. Please see the image below:

![image](https://github.com/neurosim/DNN_NeuroSim_V1.4/assets/40681739/4eea7444-5c2b-4bfe-8f2c-8496fcb921fb)

Note that when I change the memory cell to SRAM (and everything else is the same), I get normal output:

![image](https://github.com/neurosim/DNN_NeuroSim_V1.4/assets/40681739/6be97c78-7223-4d32-870b-cdc45f771546)

I did some digging and in case of ReRAM for some reason the resistances are all negative, which then results in a NaN when log is applied in "MultilevelSenseAmp::GetColumnLatency(double columnRes)" function later on.

Is there something I am doing wrong?

Best Regards.

**Comment by aethernavshulkraven-allain** [comment]
same issue any updates @pavelgolikov, how should i fix this?
